backend:
  replicaCount: 2

  image:
    repository: mayanksh786/school-backend
    tag: latest
    pullPolicy: Always

  service:
    type: ClusterIP
    port: 5000

  containerPort: 5000


frontend:
  replicaCount: 2

  image:
    repository: mayanksh786/school-frontend
    tag: latest
    pullPolicy: Always

  service:
    type: ClusterIP
    port: 80

  containerPort: 80


ingress:
  enabled: true
  className: nginx

  host: school.example.com

  paths:
    frontend: /
    backend: /api