version: "3.8"

services:

  mongo:
    image: mongo
    container_name: school-mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  backend:
    image: mayanksh786/school-backend:latest
    container_name: school-backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo

  frontend:
    image: mayanksh786/school-frontend:latest
    container_name: school-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend


volumes:
  mongo-data: