apiVersion: v1
kind: Secret

metadata:
  name: backend-secret
  namespace: school-management

type: Opaque

stringData:

  MONGO_URI: "mongodb+srv://mayanksh343_db_user:wHCoYmV2SnjhAdq1@cluster0.yxmhtot.mongodb.net/?appName=Cluster0"
 
